In [7]:
import numpy as np
# Crop yields for 4 farms over 5 years (tons/hectare)
yeilds=np.array([
    [45, 48, 52, 49, 53],
    [38, 41, 39, 44, 42],
    [52, 55, 58, 56, 60],
    [41, 43, 45, 47, 46]
])
# Weather impact factors for each year (1D array - broadcasts across farms)
weather_factors=np.array([1.0,0.95,1.05,0.98,1.02])

# Broadcasting: adjust all farm yields by weather factors
adjusted_yields=yeilds*weather_factors
print("\n WEATHER-ADJUSTED YIELDS:")
print(adjusted_yields.round(2))

# Boolean Indexing: find exceptional years
exceptional=adjusted_yields>55
print("\n EXCEPTIONAL YIELDS(>55):")
print(adjusted_yields[exceptional])

# Conditionsal Operations: Classify yields
categories=np.where(
    adjusted_yields>50 , 'High',
    np.where(adjusted_yields>40,'Medium','Low')
    )
print("\n YIELD CATEGORIES:")
print(categories)

# Advanced indexing: Select specific farms
selected_farms=[0,3] # Farm 1 and Farm 3
print(f"\n SELECTED FARMS YIELDS:")
print(yeilds[selected_farms])

# Multi-condition filtering
good_years=adjusted_yields[(adjusted_yields>45) & (adjusted_yields<55)]
print(f"\n GOOD PERFROMING YEARS(45-55 tons):")
print(good_years)


 WEATHER-ADJUSTED YIELDS:
[[45.   45.6  54.6  48.02 54.06]
 [38.   38.95 40.95 43.12 42.84]
 [52.   52.25 60.9  54.88 61.2 ]
 [41.   40.85 47.25 46.06 46.92]]

 EXCEPTIONAL YIELDS(>55):
[60.9 61.2]

 YIELD CATEGORIES:
[['Medium' 'Medium' 'High' 'Medium' 'High']
 ['Low' 'Low' 'Medium' 'Medium' 'Medium']
 ['High' 'High' 'High' 'High' 'High']
 ['Medium' 'Medium' 'Medium' 'Medium' 'Medium']]

 SELECTED FARMS YIELDS:
[[45 48 52 49 53]
 [41 43 45 47 46]]

 GOOD PERFROMING YEARS(45-55 tons):
[45.6  54.6  48.02 54.06 52.   52.25 54.88 47.25 46.06 46.92]


In [17]:
import numpy as np
# Create a 10X5 array with values 0 to 49
a=np.arange(50).reshape(10,5)
print("\n ORIGINAL ARRAY(10X5):\n ",a)


 ORIGINAL ARRAY(10X5):
  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [25]:
# Select all rows were the first feature(column 0) is greater than 20
print(a[:])
print(a[:0])
print(a[:1])
selected_rows=a[a[:,0]>20]
print("\n ROWS WHERE FIRST FEATURE >20 :\n ", selected_rows)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[]
[[0 1 2 3 4]]

 ROWS WHERE FIRST FEATURE >20 :
  [[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [40]:
import numpy as np

a=np.arange(21).reshape(3,7)
print("\n ANOTHER ARRAY:\n",a)

print("\n TRIAL 1 \n ",(a[:]))  # This will print all the elements of the matrix in the same order
print("\n TRIAL 2 \n ",a[:,0])  # This will print the eleents that are present in the 0th index
print("\n TRIAL 3 \n ", a[:,1]) # In the same manner this will print the elemnts present in the 1st index
print("\n TRIAL 4 \n ",a[a[:,0]>10])   # This performs boolean indexing. It first creates a boolean array by checking which elements in the first column (a[:,0]) are greater than 10.
                                      # Then, it uses this boolean array to select and print only those rows from a where the condition was True.


 ANOTHER ARRAY:
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]

 TRIAL 1 
  [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]

 TRIAL 2 
  [ 0  7 14]

 TRIAL 3 
  [ 1  8 15]

 TRIAL 4 
  [[14 15 16 17 18 19 20]]
