In [ ]:
import numpy as np
x=np.arange(10)
x[x%2==0]*=2
print(x)

[ 0  1  4  3  8  5 12  7 16  9]


In [ ]:
import numpy as np
x=np.arange(10)
x[::2]*2    # This line first selects every second element of x (elements at indices 0, 2, 4, 6, 8), which would be [0, 2, 4, 6, 8]. #
            # It then multiplies these selected elements by 2, resulting in [0, 4, 8, 12, 16]. However, this result is not assigned back to x, meaning the original array x remains unchanged.
print(x)

[ 0  4  8 12 16]


In [ ]:
import numpy as np
x=np.arange(10)
x=x[::2]*2    # x[::2] selects every second element of the array x, starting from the first element (index 0). This results in a temporary array [0, 2, 4, 6, 8].
              # *2 then multiplies each element of this temporary array by 2, yielding [0, 4, 8, 12, 16].
print(x)

[ 0  4  8 12 16]


In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
a[a>3]=0
print(a)

[1 2 3 0 0 0]


In [6]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])
mask = np.array([True, False, True, False, True])
b=a[mask]
print(b)

[10 30 50]


In [7]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
mask = np.array([True, False, True, False, True, False])
b = a[mask] * 10
print(b)

[10 30 50]


Suppose a has shape (2,3) and b has shape (3,). What is the shape of a + b under NumPy broadcasting rules, assuming the operation is valid?

ANSWER:
*NumPy broadcasting starts by comparing shapes from the rightmost (trailing) dimension. If the arrays have a different number of dimensions, the shape of the smaller array is padded with 1s on its left side.
Shape of a=(2,3)
Shape of b=(3,) prepended with 1 becomes (1,3)
*Two dimensions are compatible if they are equal, or if one of them is 1.
*Trailing dimension: Both are 3.They match.
Leading dimension a has 2 and b(padded) has 1
. Since one is 1 ,they are compatible.
*Dimension 1: max(2,1)=2
Dimension 2:max(3,3)=3



In [8]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
a[a[:, 1] % 2 == 0]
# a[:, 1]: This selects all elements from the second column of the array a, resulting in [2, 4, 6].
# % 2 == 0: This performs a modulo operation on the selected column and checks if each element is evenly divisible by 2, generating a boolean array: [True, True, True].
# a[...]: This uses the resulting boolean array to select only the rows in a where the corresponding boolean value is True.


array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
a[:, a[1, :] % 2 == 0]
# The code attempts to use boolean array indexing where the indices applied to the first axis of array a are generated from the second axis. This causes an IndexError because the shape of the boolean mask does not match the axis it is being applied to [1].
# Specifically: a has the shape (3, 2).
# a[1, :] % 2 == 0 evaluates to a 1-dimensional boolean array of shape (2,), which is [False, True].
# The slicing a[:, ...] attempts to apply this 2-element mask to the first axis of a, which has 3 elements.


array([[2],
       [4],
       [6]])

In [10]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
a[a % 2 == 0]
# he code a[a % 2 == 0] returns the flattened array of all even numbers in the original array a

array([2, 4, 6])

In [13]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
a[a[:, 0] % 2 == 0, 1]
# The code a[a[:, 0] % 2 == 0, 1] selects elements from the second column (index 1) of the NumPy array a where the corresponding element in the first column (index 0) is even.
# a[:, 0]: This slices the array to get all elements in the first column: [1, 3, 5].
# a[:, 0] % 2 == 0: This applies a modulo operation and a comparison to create a boolean mask, which evaluates to [False, False, False] because all elements in the first column are odd.
# a[..., 1]: This attempts to use the boolean mask to select rows and then retrieve the second column.


In [12]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
mask = (x % 2 == 0)
print(mask)

[False  True False  True False]


In [14]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20, 30])
c=a+b
print(c)

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [15]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
c=a+b
print(c)

[[11 22]
 [13 24]]


In [16]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])
idx = np.array([4, 0, 4, 1])   # Index numbers of 'a' array will get printed
a[idx]
# The operation a[idx] results in a copy of the data where the output shape is determined by the index array rather than the original array, producing the array ([50,10,50,20])
# a[idx] returns a new array [50, 10, 50, 20], which is a re-ordered copy determined by the indices, and modifying it does not change a.

array([50, 10, 50, 20])

In [17]:
a = np.array([[1, 2], [3, 4], [5, 6]])
mask = np.array([True, False, True])
a[mask]

array([[1, 2],
       [5, 6]])

In [18]:
a = np.array([1, 2, 3])
b=a*2
print(b)

[2 4 6]


In [19]:
a = np.array([1, 2, 3, 4, 5])
a[a>2]     #Here Boolean Indexing occurs

array([3, 4, 5])

In [20]:
a = np.array([1, 2, 3, 4, 5])
a[2:]    # Here slicing occurs

array([3, 4, 5])

In [21]:
import numpy as np
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
mask = np.array([True, False, True])
arr[mask]



array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [22]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 0, 1], [0, 1, 0]], dtype=bool)
a[b]   # When you index a NumPy array with a boolean mask of the same shape, the operation extracts the elements where the mask is True.
# Row 0: [1, 0, 1] -----> [True, False, True]
# Row 1: [0, 1, 0] -----> [False, True, False]

array([1, 3, 5])

In [23]:
import numpy as np
a = np.arange(50).reshape(10, 5)
#You want to select all rows where the first feature #(column 0) is greater than 20:
selected_rows = a[a[:, 0] > 20]
a[:,0]>20

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
c=a+b
print(c)

[[11 22 33]
 [14 25 36]]


In [27]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a[:,[False,True]]

array([[2],
       [4],
       [6]])

In [31]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
(a>2) & (a<6)


array([[False, False,  True],
       [ True,  True, False]])

In [33]:
a = np.array([10, 20, 30, 40, 50])
mask = a > 25   # Boolean masking selects elements based on a condition applied to the data
a[mask]


array([30, 40])

In [34]:
a = np.array([10, 20, 30, 40, 50])
idx = np.array([2, 3])
a[idx]      # integer indexing selects elements based on explicit positions

array([30, 40])