In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 0-D Array
import numpy as np
arr=np.array(40)
print(arr)

40


In [ ]:
# 1-D Array
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)


[1 2 3 4 5]


In [ ]:
# 2-D Array
import numpy as np
arr=np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3-D Array
import numpy as np
arr=np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
import numpy as np                                # ndim is an attribue that return an integer that tells us how many dimensions the array has

a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3], [4,5,6]])
d=np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
# Higher Dimensional Array
import numpy as np

arr=np.array([1,2,3], ndmin =5)
print((arr))
print("Number of Dimensions:", arr.ndim)



[[[[[1 2 3]]]]]
Number of Dimensions: 5


In [ ]:
# ACCESS ARRAY ELEMENTS
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
# ACCESS ARRAY ELEMENTS
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+ arr[3])

7


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])

# 2-D Array(matrix)
np.array([[1,2,3], [4,5,6]])

# USING BUILT-IN FUNCTIONS
zeros=np.zeros((3,4))
ones=np.ones((2,3))
range_arr=np.arange(0,10,2)
linspace=np.linspace(0,1,5)
identity=np.eye(3)
random_arr=np.random.rand(3,4)

print(zeros)
print("-----------------------------------------")
print(ones)
print("-----------------------------------------")
print(range_arr)
print("-----------------------------------------")
print(linspace)
print("-----------------------------------------")
print(identity)
print("-----------------------------------------")
print(random_arr)
print("-----------------------------------------")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------------------------------------
[[1. 1. 1.]
 [1. 1. 1.]]
-----------------------------------------
[0 2 4 6 8]
-----------------------------------------
[0.   0.25 0.5  0.75 1.  ]
-----------------------------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----------------------------------------
[[0.44333976 0.90863841 0.47511838 0.18990072]
 [0.1659007  0.2996405  0.75955409 0.48198092]
 [0.51968905 0.72296528 0.89536826 0.88723581]]
-----------------------------------------


In [ ]:
import numpy as np
random=np.random.rand(5,5)
print(random)

[[0.79319964 0.271892   0.51311486 0.75173931 0.5381604 ]
 [0.65748327 0.14638912 0.67065206 0.63648531 0.97608081]
 [0.89675199 0.33097383 0.87576504 0.13443155 0.79315984]
 [0.3962324  0.00564602 0.62566518 0.19495796 0.08949119]
 [0.27046545 0.62495311 0.76889321 0.65158727 0.29521239]]


In [ ]:
import numpy as np
random=3+(5-3)*np.random.rand(5,5)   # A+(B-A)*np.random.rand() should be used to specify the number range
print(random)                          # The built in range is 0 to 1

[[4.54538569 4.7252185  4.31342706 4.06456266 3.23569341]
 [3.75830573 4.96118489 4.16646747 4.00180066 3.37249795]
 [4.91404686 3.37968789 4.58596174 3.10101617 4.73693117]
 [3.54235897 4.28744685 4.02554038 3.67340227 4.17113794]
 [3.38439405 3.17011056 4.07306689 3.30047155 4.01344754]]


In [ ]:
import numpy as np
c=np.array([1,2,3,4,5])[1:]
print(c)



[2 3 4 5]


In [ ]:
import numpy as np
random=np.random.rand(4,5)
print(random)

[[0.93596254 0.068494   0.29178441 0.56227383 0.38279138]
 [0.35483615 0.37920777 0.53654131 0.33268867 0.98908472]
 [0.32506549 0.62635901 0.08872747 0.11887952 0.4666335 ]
 [0.24849722 0.72793481 0.45149443 0.52358297 0.22141472]]


In [ ]:
# NumPy ARRAY ATRRIBUTES AND FUNCTIONS
a=np.array([1,2,3])     # Converts a list into  NumPy array
print(a)


[1 2 3]


In [ ]:
a=np.array([[1,2,3], [4,5,6]])
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)
add=np.sum(a)
print(add)
column_mean=np.mean(a,axis=0)
print(column_mean)
row_mean=np.mean(a,axis=1)
print(row_mean)
max=np.max(a)
print(max)
min=np.min(a)
print(min)
divide=np.max(a)/np.min(a)
print(divide)



(2, 3)
int64
6
2
21
[2.5 3.5 4.5]
[2. 5.]
6
1
6.0


In [ ]:
# INDEX OF EXTREME VALUE
b=np.array([10,50,100])
extreme=np.argmax(b)
print(extreme)

2


In [ ]:
import numpy as np
crop_yields=np.array([
    [12.5, 13.2, 14.1, 13.8, 15.2],
    [10.3, 11.5, 10.8, 12.1, 11.9],
    [15.1, 14.8, 16.2, 15.5, 16.8],
    [11.2, 10.9, 12.3, 11.7, 12.8]
])

print("CROP YIELDS ARRAY(in tons):")
print(crop_yields)
print(f"\n Shape: {crop_yields.shape}")
print(f"\n Data Type: {crop_yields.dtype}")
print(f"\n Total Elements: {crop_yields.size}")
print(f"\n Number of Dimensions: {crop_yields.ndim}")

# AGRICULTURAL ANALYSIS OPERATIONS
total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1)
avg_yield_per_season=np.mean(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)

print(f"\n TOTAL PRODUCTION:{total_yield}tons")
print(f"\n AVERAGE YIELD PER FARM:{avg_yield_per_farm}tons")
print(f"\n AVERAGE YIELD PER SEASON :{avg_yield_per_season}tons")
print(f"\n MAXIMUM YIELD:{max_yield}tons")
print(f"\n MINIMUM YIELD:{min_yield}tons")

# TO FIND THE BEST PERFORMING FARM
best_farm=np.argmax(avg_yield_per_farm)
print(f"\n BEST PERFORMING FARM:Farm{best_farm+1}")
print(f"\n THEIR AVERAGE YIELD:{avg_yield_per_farm[best_farm]:.2f}tons")

CROP YIELDS ARRAY(in tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

 Shape: (4, 5)

 Data Type: float64

 Total Elements: 20

 Number of Dimensions: 2

 TOTAL PRODUCTION:262.7tons

 AVERAGE YIELD PER FARM:[13.76 11.32 15.68 11.78]tons

 AVERAGE YIELD PER SEASON :[12.275 12.6   13.35  13.275 14.175]tons

 MAXIMUM YIELD:16.8tons

 MINIMUM YIELD:10.3tons

 BEST PERFORMING FARM:Farm3

 THEIR AVERAGE YIELD:15.68tons


In [ ]:
import numpy as np
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(arr)
np.sort(arr)

[2 1 5 3 7 4 6 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
import numpy as np
x = np.array([6, 7, 5])    # This arranges the numbers in ascending order but their index numbers will be specified in the output
np.argsort(x)

array([2, 0, 1])

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a,b))   # Will join the 2 arrays and make it a single array


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y),axis=0)   # Even if axis=0 is not mentioned it will interpret the same as above itself

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
import numpy as np
a = np.arange(6)
print(a)
b = a.reshape(3, 2)   # This will arrange the specifed numbers within the mentioned range in the specified matrice shape
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
#Indexing and slicing

data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])
print("\n")
five_up = (a >= 5)
print(a[five_up])
print("\n")
divisible_by_2 = a[a%2==0]
print(divisible_by_2)
print("\n")
c = a[(a > 2) & (a < 11)]    # Logical AND
print(c)
print("\n")
five_up = (a > 5) | (a == 5)    # Logical OR
print(five_up)

[1 2 3 4]


[ 5  6  7  8  9 10 11 12]


[ 2  4  6  8 10 12]


[ 3  4  5  6  7  8  9 10]


[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [7]:
import numpy as np
a=np.array([[1,2,],[3,4]])
b=(a > 2) | (a < 0 )
print(b)

[[False False]
 [ True  True]]


BROADCASTING

In [9]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b6

array([2., 4., 6.])