In [ ]:
import numpy as np
# Nutrients requirements for 3 crop(N,P,K in kg/ha)
# Rows: Crops(Whaeat,Corn,Rice)
# Columns:Nutrients(Nitogen,Phosphorous,Potassium)
nutrint_needs=np.array([
    [120,60,80],
    [120,75,100],
    [100,50,75]
])

# Available Fertilizer Compostion(% of N,P,K)
# Rows:Fertilizer type
# Columns:Nutrient content
fertilizer_composition=np.array([
    [0.20,0.10,0.15],
    [0.15,0.20,0.10],
    [0.10,0.15,0.25]
])
print("\n NUTRIENT REQUIREMENTS (kg/ha):")
print(nutrint_needs)
print("\n FERTILIZER COMPOSITION (%):")
print(fertilizer_composition)

# Matrix transpose example
print("\n TRANSPOSED NUTRIENT NEEDS(Nutreints X Crops):")
print(nutrint_needs.T)

# Calculate fertilizer amounts(solving system of equations)
# This would normally require optimization but for demonstration
total_nutrients_per_crop=np.sum(nutrint_needs,axis=1)
print(f"\n TOTAL NUTRIENTS NEEDED PER CROP:{total_nutrients_per_crop} kg/ha")

# Matrix multiplication: Calculate nutrient delivery
# If we appluy 100kg of each fertilizer type
fertilizer_application=np.array([100,100,100]) # kg of each type
nutrients_delivered=np.dot(fertilizer_application,fertilizer_composition)
print(f"\n NUTRIENTS FROM 100 KG OF EACH FERTILIZER :{nutrients_delivered}")

# Calculate determinant for checking if matrix is invertible
det=np.linalg.det(fertilizer_composition)
print(f"\n DETERMINANT Of FERTILIZER MATRIX:{det: .6f}")

# Idenitity matrix example(scaling factor)
scaling=np.eye(3)*1.1 # 10% increase
enhanced_needs=np.dot(nutrint_needs,scaling)
print("\n ENHANCED NUTRIENT NEEDS (10 % increase):")
print(enhanced_needs)



 NUTRIENT REQUIREMENTS (kg/ha):
[[120  60  80]
 [120  75 100]
 [100  50  75]]

 FERTILIZER COMPOSITION (%):
[[0.2  0.1  0.15]
 [0.15 0.2  0.1 ]
 [0.1  0.15 0.25]]

 TRANSPOSED NUTRIENT NEEDS(Nutreints X Crops):
[[120 120 100]
 [ 60  75  50]
 [ 80 100  75]]

 TOTAL NUTRIENTS NEEDED PER CROP:[260 295 225] kg/ha

 NUTRIENTS FROM 100 KG OF EACH FERTILIZER :[45. 45. 50.]

 DETERMINANT Of FERTILIZER MATRIX: 0.004625

 ENHANCED NUTRIENT NEEDS (10 % increase):
[[132.   66.   88. ]
 [132.   82.5 110. ]
 [110.   55.   82.5]]
